### ISSUE TITLE
hello,i modify project to cpp, but the func name of VmxVmexitHandler was called by asm in Exit.c, how to build it with cmake?

### ISSUE THREAD

**Issue by ddkwork** [SinaKarvandi/Hypervisor-From-Scratch#10]
https://github.com/DiskGetor/Driver/

**Comment by SinaKarvandi** [comment]
hello, unfortunately, I don't have any experience with CMAKE, but you have to find a way of running asm in cpp using make, maybe this can help: https://stackoverflow.com/questions/15132185/mixing-c-and-assembly-sources-and-build-with-cmake
