### ISSUE TITLE
Cannot run anything as admin

### ISSUE THREAD

**Issue by armvirus** [SinaKarvandi/Hypervisor-From-Scratch#13]
When the hypervisor is running. (PART 8) I cannot run any process as admin. it gives error like this:
https://cdn.discordapp.com/attachments/713358396346073122/810214626565947432/unknown.png
which is STATUS_ILLEGAL_INSTRUCTION. nothing in the vmexit handler is called when this happens (related to it)

**Comment by SinaKarvandi** [comment]
It's weird, if you can provide more information on why this happens, we might find the solution.
Btw, please test HyperDbg (https://github.com/HyperDbg/HyperDbg), it's a newer version of Hypervisor From Scratch, and check whether you experience the same error or not.

**Comment by armvirus** [comment]
I tried to figure it out but it doesn't make sense i thought its maybe with capturing / restoring the guest registers but im not even sure. can you try it yourself. run the driver open the usermode application so the HV is running. then try running notepad as admin

**Comment by armvirus** [comment]
also idk if i read this write but "(HyperDbg is NOT in a WORKING STATE - YOU SHOULD NOT USE IT, but you can observe codes, please wait for first release in late March 2021)"

**Comment by SinaKarvandi** [comment]
I ran Hypervisor From Scratch on my Laptop (Skylake processor), and it works perfectly (I can open the Notepad.exe as administrator).
HyperDbg is almost done; we just not test it yet, but it works perfectly for the simple features. You can use it too.

**Comment by armvirus** [comment]
i ran the hv from scratch part 8 again on my main pc and laptop so not just my VM. made sure hv is launched (usermode application is running and called DrvCreate to launch hv) and i get the error still when i try running anything as admin. can you add me on discord. flushin#9408 i hope we can fix this issue.

**Comment by armvirus** [comment]
i tried using the vmcs setup from hyperdbg and still have the same issue.

**Comment by SinaKarvandi** [comment]
nothing is different in vmcs of HyperDbg and hypervisor from scratch, they're almost the same.
Run HyperDbg using ".connect local" and "load vmm" commands.

**Comment by armvirus** [comment]
i compiled HyperDbg but when i try run it it says path not found????? with sc create/sc start

**Comment by SinaKarvandi** [comment]
You can load it automatically without any external command. you should run :   ".connect local" and "load vmm" commands.

**Comment by Souhardya** [comment]
I'm hitting the same issue does that have to do something for the NtCreateFile hook implemented? 

I do keep hitting first chance exceptions like this Unhandled exception 0xc000001d, hit in C:\Windows\System32\svchost.exe -k NetworkService -p -s DoSvc: 

but I  don't think it's related 

As long as the UM app keeps connected .. you basically cant run anything as an admin

**Comment by SinaKarvandi** [comment]
So, what's your processor model? and your Windows version? and have you tested it with the "Debug" version of HyperDbg?
Errors like this are really hard to investigate.
