### ISSUE TITLE
hook for address range?

### ISSUE THREAD

**Issue by xSanx** [SinaKarvandi/Hypervisor-From-Scratch#14]
can I put a hook on a range (section) of memory cells?

**Comment by SinaKarvandi** [comment]
What kind of hok do you mean? read-write or execute?

**Comment by xSanx** [comment]
> Что за хок ты имеешь в виду? читать-писать или выполнять?

any ... read a range of physical memory where structures bios

**Comment by SinaKarvandi** [comment]
Use HyperDbg's !monitor command for this purpose : 
https://docs.hyperdbg.com/commands/extension-commands/monitor
