### ISSUE TITLE
Tutorial on how to use the hypervisor to virtualize a single app

### ISSUE THREAD

**Issue by danyhm** [SinaKarvandi/Hypervisor-From-Scratch#15]
Hello,

can you please make a tutorial on how to virtualize an existing app (.exe in windows) using the hypervisor?

also, is it possible to make a generic sandbox app using the hypervisor which virtualized other apps? similar to what VMware ThinApp and other portable app makers do.

I know software like ThinApp doesn't use the hardware on the CPU to sandbox the app but I just want to gain insight on how it's done if we were to use the hypervisor.

by the way, your tutorials are the best I could find out there about hypervisors, great job!

**Comment by SinaKarvandi** [comment]
Hello,
Thanks a lot for reading the tutorial.
Actually, it's a longstanding to-do for me, and it probably takes long to create such a tutorial as I'm so busy these days working on HyperDbg Debugger. But, sure, I'll try to make such a tutorial ASAP

Again, thanks for reading and this feedback.

**Comment by danyhm** [comment]
@SinaKarvandi don't mention it.
Just to be sure , it is possible to virtualize just a single application such as notepad.exe using the micro hypervisor, right?

**Comment by SinaKarvandi** [comment]
Yep, of course, it's possible, but I don't have any idea how to implement such a thing right now. But when you're operating on vmx-root mode, you are even more privileged than the operating system.

**Comment by danyhm** [comment]
@SinaKarvandi of course i know we are priviledged that's how Vmware and others load another operating system. But my concern is towards doing such a thing without needing to boot anothet OS. I want to know if it's possible to virtualize the app inside the current Host system with minimum overhead.

**Comment by SinaKarvandi** [comment]
I mean definitely, it's possible, it's a matter of time and implementation. But I think that should not be that complicated.

**Comment by danyhm** [comment]
Thanks for your guidance. I'll put here a link for reference for anyone who might encounter something similar
https://github.com/ionescu007/Simpleator
Is supposed to virtualize exactly a single executable. however, I could not get it to work.
