### ISSUE TITLE
Hyper-V and EPT

### ISSUE THREAD

**Issue by AkumaRRR** [SinaKarvandi/Hypervisor-From-Scratch#17]
If I comment the test code in Part8
```
//////////// test //////////// 
//HiddenHooksTest();
//SyscallHookTest();
////////////////////////////// 
```
I get a PAGE_FAULT_IN_NONPAGED_AREA on Hyper-V (no problem on VMWare).
Same with Part7. I can't figure out why. What's the problem with Hyper-V?

**Comment by SinaKarvandi** [comment]
Honestly, I didn't work on this for a long time, so, the errors might be expected.

I have to retest these codes on these environments again and re-write some of the parts of Hypervisor From Scratch. But now, I'm really busy making the first release of HyperDbg. As long as I know, HyperDbg has a problem on Hyper-V too, but we're not supposed to support Hyper-V on the first release. So, after releasing the first version, I'll come back again to see what's the problem with both HyperDbg and Hypervisor From Scratch on hyper-v and update the post and codes.

**Comment by SinaKarvandi** [comment]
Please also ping me if you find the cause of the problem. The last time that I test in on Hyper-V, I figured out that there is something wrong with the memory manager of Hyper-V's nested virtualization, the problems are solved if we invalidate EPT on each VM-exit but that's definitely not a good option as it makes the system substantially slower.

**Comment by AkumaRRR** [comment]
Thank you for your reply.
I sort of figured out it could be a problem related with caching.
I'm gonna try to find the cause of the problem and from time to time I'll also take a look at HyperDbg to see if you find a proper fix in the meantime.
