### ISSUE TITLE
hook NtQuerySystemInformation question

### ISSUE THREAD

**Issue by hhuiwang** [SinaKarvandi/Hypervisor-From-Scratch#26]
Several functions have this problem for a long time (my English is not good, so I can only record to show my problem on the screen, sorry)
![G](https://github.com/user-attachments/assets/f25df83a-ed1a-45e1-ac02-9218748c8d2f)
![20240905120758](https://github.com/user-attachments/assets/1e9e7c03-027e-4de1-9afb-6613be9e954c)
![20240905120837](https://github.com/user-attachments/assets/ca45d77b-6620-4a94-869f-95c4f390ce58)
![20240905120853](https://github.com/user-attachments/assets/f6eea993-c35d-4379-8b08-fa69335f1eb2)

Try to read the code for the HyperDbg project, but that project was just too hard for a rookie like me

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue.

It's actually expected since I've tons of revisions to the HyperDbg for EPT hooks. I think the best approach here is to use HyperDbg for real-world scenarios and keep the tutorial as easy as possible.

**Comment by hhuiwang** [comment]
Thanks for your reply. 
Can you give this BUG advice?  I have been reading your blog and trying to find out the problem, but I really can't solve it. I have to ask you, this question has been bothering me for a long time.

**Comment by SinaKarvandi** [comment]
Maybe it's a problem with the length disassembler engine. Hypervisor From Scratch uses a really light LDE which is not working most of the time. But, HyperDbg uses Zydis which is perfect and correct disassembler.

**Comment by hhuiwang** [comment]
> 也许是长度反汇编引擎的问题。Hypervisor From Scratch 使用非常轻量级的 LDE，大多数时候都不起作用。但是，HyperDbg 使用 Zydis，它是完美且正确的反汇编器。

Thank you for your advice
