### ISSUE TITLE
ProtectedMode.c doesn't seem

### ISSUE THREAD

**Issue by ghost** [SinaKarvandi/Hypervisor-From-Scratch#3]
C1083 Cannot open source file: 'ProtectedMode.c': No such file or directory
This file doesn't seem in Project.

**Comment by SinaKarvandi** [comment]
'ProtectedMode.c' is for the future parts (as long I find a remote computer) ... so it was empty and seems that when I upload this file, GitHub decided to remove empty files, BTW I add a simple /* test */ as the 'ProtectedMode.c'.
