### ISSUE TITLE
Wrong Symbolic Name used in DriverUnload

### ISSUE THREAD

**Issue by KnoooW** [SinaKarvandi/Hypervisor-From-Scratch#4]
In DriverUnload routine:

RtlInitUnicodeString(&usDosDeviceName, L"\\**Device**\\MyHypervisorDevice");

**should be**

RtlInitUnicodeString(&usDosDeviceName, L"\\**DosDevices**\\MyHypervisorDevice");

**Comment by SinaKarvandi** [comment]
Fixed.
