### ISSUE TITLE
[Part 2: MyHypervisorDriver] Multiple errors when compiling with with Visual Studio 2019

### ISSUE THREAD

**Issue by thatreguy** [SinaKarvandi/Hypervisor-From-Scratch#6]
![Annotation 2020-01-22 002740](https://user-images.githubusercontent.com/44264798/72834186-4a7e7900-3cae-11ea-9bd9-b48510e0891e.png)

**Comment by SinaKarvandi** [comment]
Hello, 

You're using an Enterprise version of VS? Did you install WDK without error?

**Comment by thatreguy** [comment]
I'm using the community express edition. Wdk was installed properly last I checked. Will try this again.

**Comment by EquilMinis** [comment]
Sorry for commenting on an already closed issue, but I had this same issue when I I realized I was compiling in x32 bit mode (MASM seems to work differently on x32 and x64 bit, requires different directives..etc.)

**Comment by SinaKarvandi** [comment]
Hello

Hypervisor From Scratch is an x64 project by design, you can't use it in 32-bit machines. Please try to compile it with x64 configuration.
