### ISSUE TITLE
[Part 2: MyHypervisorApp] VMX operation is shown to be not supported even though virtualization is enabled in VMWare Player

### ISSUE THREAD

**Issue by thatreguy** [SinaKarvandi/Hypervisor-From-Scratch#7]
![vmx](https://user-images.githubusercontent.com/44264798/72834721-69313f80-3caf-11ea-9242-0b5d6e0da809.png)

**Comment by SinaKarvandi** [comment]
It simply checks for the presence of a bit in CPUID, you can set this bit manually in .vmx file of your VM, it solves the problem, or you can remove this check function from MyHypervisorApp !!!! by the way, I don't know whether VMWare Player supports Nested Virtualization or not, make sure it supports then try to run the driver. I know VMWare workstation supports but don't know about the player.

**Comment by TempAccountNull** [comment]
> ![vmx](https://user-images.githubusercontent.com/44264798/72834721-69313f80-3caf-11ea-9242-0b5d6e0da809.png)

Hello, may this message find you well. 
Little information is said about stuff like this and setting it up, So hopefully this will help in the future.
# Getting started
- If this happens please ensure that your
  - Processor supports VMX instructions
  - Not using WSL (Windows Subsystem for Linux)
  - Not using Hyper-V. 
  - Not using an Antivirus that uses a hypervisor such as Kaspersky)
> [!IMPORTANT]  
> **If you have these installed you cannot use the hypervisor as you can only have one installed at a time.**

## Checking if your processor supports VMX instruction sets
- Open run by pressing (windows + R)
  - type cmd.exe and press enter
  - Type the following command and hit enter
```
wmic cpu get VirtualizationFirmwareEnabled, VMMonitorModeExtensions
```
IF you see the following you can continue.
```
VirtualizationFirmwareEnabled  VMMonitorModeExtensions
TRUE                           TRUE
```
## Checking if your already running a hypervisor.
- Open run by pressing (windows + R)
  - type cmd.exe and press enter
  - Type systeminfo and hit enter and look all the way down for
```
Guest Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```
> [!IMPORTANT]  
> **IF you see this message then a hypervisor is already running. You will need to disable it.**
### What you should see
```
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```
## Setting up a VMWare environment
- Safely shut down your machine
  - right click your machine on the left-hand side and click `Open vm directory` 
    - look for your named machine's vmx file. (open this in your preferred editor)
  - add the following lines to your vmx file and save it and reboot your machine.
```
vhv.enable = "TRUE"
monitor.virtual_exec = "hardware"
monitor.virtual_mmu = "hardware"
hypervisor.cpuid.v0 = "TRUE"
```
# Remedies / Fixes
- For WSL, please run the following to disable it and reboot. (You will not lose any data).
```cmd
dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /norestart
dism.exe /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux /norestart
```

Have fun!
